export enum EventTypeDispatchEnum {
  CREATE_PACIENTE = "CREATE_PACIENTE",
  UPDATE_PACIENTE = "UPDATE_PACIENTE",
  DELETE_PACIENTE = "DELETE_PACIENTE",
  CREATE_DADO_SAUDE_PACIENTE = "CREATE_DADO_SAUDE_PACIENTE",
  UPDATE_DADO_SAUDE_PACIENTE = "UPDATE_DADO_SAUDE_PACIENTE",
  DELETE_DADO_SAUDE_PACIENTE = "DELETE_DADO_SAUDE_PACIENTE",
}
